

1.   Nombre: Maria Fernanda Peñaranda Villalobos
2.   Código: 20221987

In [130]:
import pandas as pd
tabla="https://github.com/Maferenv/PC2/raw/refs/heads/main/HDI.xlsx"

In [131]:
tabla

'https://github.com/Maferenv/PC2/raw/refs/heads/main/HDI.xlsx'

In [132]:
HDI=pd.read_excel(tabla, header=4)

In [133]:
HDI

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank
0,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
1,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
4,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
HDI_new=HDI.copy()

In [135]:
HDI_new.drop(columns=['Unnamed: 0','Unnamed: 3','Unnamed: 5','Unnamed: 7','Unnamed: 9','Unnamed: 11','Unnamed: 13'], inplace=True)

In [136]:
HDI_new

,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,2021,2021,2021,2021,2021,2021,2020
2,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
4,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
...,...,...,...,...,...,...,...,...
267,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
HDI_new = HDI_new.iloc[:225]
HDI_new

,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,2021,2021,2021,2021,2021,2021,2020
2,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
4,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
...,...,...,...,...,...,...,...,...
220,Small island developing states,0.73,70.325547,12.422289,9.08964,16782.329527,—,—
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,Organisation for Economic Co-operation and Dev...,0.899,78.987605,16.459253,12.267755,45086.969067,—,—
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,World,0.732,71.365465,12.780907,8.617461,16752.082922,—,—

In [138]:
HDI_new.rename(columns={'Unnamed: 1':'Country'}, inplace=True)
HDI_new

<ipython-input-138-76e34cf37ecc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HDI_new.rename(columns={'Unnamed: 1':'Country'}, inplace=True)

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,2021,2021,2021,2021,2021,2021,2020
2,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
4,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
...,...,...,...,...,...,...,...,...
220,Small island developing states,0.73,70.325547,12.422289,9.08964,16782.329527,—,—
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,Organisation for Economic Co-operation and Dev...,0.899,78.987605,16.459253,12.267755,45086.969067,—,—
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,World,0.732,71.365465,12.780907,8.617461,16752.082922,—,—

In [139]:
HDI_new= HDI_new.iloc[:202]
HDI_new

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,2021,2021,2021,2021,2021,2021,2020
2,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
4,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
...,...,...,...,...,...,...,...,...
197,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..,..,..
199,Monaco,..,85.9463,..,..,..,..,..
200,Nauru,..,63.617,11.69042,..,17729.74084,..,..
201,Somalia,..,55.2803,..,..,1017.96785,..,..

In [146]:
HDI_new = HDI_new.drop(columns=['HDI rank','GNI per capita rank minus HDI rank'])

In [154]:
HDI_new = HDI_new.drop([0,1])

In [155]:
HDI_new

,country,Human_Development_Index,Life_expentancy_at_birth,Excpected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
2,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN
3,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
4,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
5,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
6,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
...,...,...,...,...,...,...
197,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN
198,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
199,Monaco,..,85.9463,..,..,..
200,Nauru,..,63.617,11.69042,..,17729.74084
201,Somalia,..,55.2803,..,..,1017.96785

In [159]:
Nombres=['Country', 'Human_Development_Index', 'Life_expentancy_at_birth','Excpected_years_of_schooling','Mean_years_of_schooling','Gross_national_income_per_capita']

In [160]:
function = {old:new for old,new in zip(HDI_new.columns,Nombres)}

In [167]:
HDI_new.rename(columns=function, inplace=True)
HDI_new

,Country,Human_Development_Index,Life_expentancy_at_birth,Excpected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
3,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
4,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
5,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
6,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
7,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
...,...,...,...,...,...,...
196,South Sudan,0.385,54.9752,5.54251,5.72614,767.787
198,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
199,Monaco,..,85.9463,..,..,..
200,Nauru,..,63.617,11.69042,..,17729.74084
201,Somalia,..,55.2803,..,..,1017.96785

In [171]:
HDI_new=HDI_new.dropna(axis='rows',how='any', ignore_index=True)

In [172]:
HDI_new

,Country,Human_Development_Index,Life_expentancy_at_birth,Excpected_years_of_schooling,Mean_years_of_schooling,Gross_national_income_per_capita
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335
...,...,...,...,...,...,...
190,South Sudan,0.385,54.9752,5.54251,5.72614,767.787
191,Korea (Democratic People's Rep. of),..,73.2845,10.78317,..,..
192,Monaco,..,85.9463,..,..,..
193,Nauru,..,63.617,11.69042,..,17729.74084
194,Somalia,..,55.2803,..,..,1017.96785